[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "cd face_recognition_server && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd face_recognition_server && python main.py"
